
/**
 * Utilities for the Python GUI functionality
 */

import { LLMProvider } from "@/services/llmService";

/**
 * Get the appropriate Python code snippet for a specific LLM provider
 */
export const getLLMProviderPythonCode = (provider: LLMProvider): string => {
  switch (provider) {
    case "ollama":
      return `
def query_ollama(prompt, model="codellama", temperature=0.7):
    """Query local Ollama instance with the given prompt"""
    import requests
    
    endpoint = "http://localhost:11434/api/generate"
    
    try:
        response = requests.post(endpoint, json={
            "model": model,
            "prompt": prompt,
            "temperature": temperature
        })
        
        if response.status_code == 200:
            return response.json().get("response", "")
        else:
            return f"Error: {response.status_code} - {response.text}"
    except Exception as e:
        return f"Connection error: {str(e)}"
`;
    
    case "deepseek":
      return `
def query_deepseek(prompt, api_key, model="deepseek-coder", temperature=0.5):
    """Query DeepSeek API with the given prompt"""
    import requests
    
    endpoint = "https://api.deepseek.com/v1/chat/completions"
    
    try:
        response = requests.post(endpoint, 
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json"
            },
            json={
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": temperature
            }
        )
        
        if response.status_code == 200:
            return response.json().get("choices", [{}])[0].get("message", {}).get("content", "")
        else:
            return f"Error: {response.status_code} - {response.text}"
    except Exception as e:
        return f"Connection error: {str(e)}"
`;
    
    case "qwen":
      return `
def query_qwen(prompt, api_key, model="qwen", temperature=0.7):
    """Query Qwen API with the given prompt"""
    import requests
    
    endpoint = "https://api.qwen.ai/v1/chat/completions"
    
    try:
        response = requests.post(endpoint, 
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json"
            },
            json={
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": temperature
            }
        )
        
        if response.status_code == 200:
            return response.json().get("choices", [{}])[0].get("message", {}).get("content", "")
        else:
            return f"Error: {response.status_code} - {response.text}"
    except Exception as e:
        return f"Connection error: {str(e)}"
`;
    
    case "openrouter":
      return `
def query_openrouter(prompt, api_key, model="mistralai/mixtral-8x7b", temperature=0.7):
    """Query OpenRouter API with the given prompt"""
    import requests
    
    endpoint = "https://openrouter.ai/api/v1/chat/completions"
    
    try:
        response = requests.post(endpoint, 
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json"
            },
            json={
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": temperature
            }
        )
        
        if response.status_code == 200:
            return response.json().get("choices", [{}])[0].get("message", {}).get("content", "")
        else:
            return f"Error: {response.status_code} - {response.text}"
    except Exception as e:
        return f"Connection error: {str(e)}"
`;
    
    default:
      return "# LLM provider not supported";
  }
};

/**
 * Generate Python settings file content
 */
export const generatePythonSettingsFile = (settings: any): string => {
  return `
"""
Code Nexus Wizard Settings
This file is automatically generated - Do not edit manually
"""

import json
import os

# Default settings
DEFAULT_SETTINGS = {
    "editor": {
        "theme": "dark",
        "font_size": 14,
        "tab_size": 4,
        "auto_save": True,
        "line_numbers": True,
        "word_wrap": True
    },
    "llm": {
        "active_provider": "ollama",
        "settings": ${JSON.stringify(settings, null, 8).replace(/"/g, "'")}
    },
    "terminal": {
        "history_limit": 1000,
        "save_history": True
    },
    "ui": {
        "layout": "default",
        "show_file_explorer": True,
        "show_terminal": True
    }
}

# Settings file path
SETTINGS_FILE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "settings.json"
)

def load_settings():
    """Load settings from file or create default settings if file doesn't exist"""
    if os.path.exists(SETTINGS_FILE):
        try:
            with open(SETTINGS_FILE, 'r') as f:
                return json.load(f)
        except Exception as e:
            print(f"Error loading settings: {e}")
            return DEFAULT_SETTINGS
    else:
        save_settings(DEFAULT_SETTINGS)
        return DEFAULT_SETTINGS

def save_settings(settings):
    """Save settings to file"""
    try:
        os.makedirs(os.path.dirname(SETTINGS_FILE), exist_ok=True)
        with open(SETTINGS_FILE, 'w') as f:
            json.dump(settings, f, indent=4)
        return True
    except Exception as e:
        print(f"Error saving settings: {e}")
        return False

def get_setting(category, key):
    """Get a specific setting value"""
    settings = load_settings()
    return settings.get(category, {}).get(key, DEFAULT_SETTINGS.get(category, {}).get(key))

def update_setting(category, key, value):
    """Update a specific setting value"""
    settings = load_settings()
    if category not in settings:
        settings[category] = {}
    settings[category][key] = value
    return save_settings(settings)
`;
};

/**
 * Generate a complete Python script with proper escape characters
 */
export const generateFullPythonScript = (llmSettings: any): string => {
  // This would generate the complete Python script based on user settings
  // For now, we'll return a placeholder
  return `#!/usr/bin/env python3
"""
Code Nexus Wizard - Python Edition
A comprehensive code development environment with LLM integration
"""

import os
import sys
import tkinter as tk
from tkinter import ttk, scrolledtext, filedialog, messagebox
import threading
import json
import subprocess
import webbrowser
from datetime import datetime
import re
import tempfile
import platform
import shutil
from tkinter.font import Font

# Check for required packages and install if missing
REQUIRED_PACKAGES = [
    "requests",
    "python-dotenv",
    "pygments",
    "pillow",
]

def check_and_install_dependencies():
    """Check for required packages and install if missing"""
    missing_packages = []
    
    try:
        import importlib.metadata as importlib_metadata
    except ImportError:
        import importlib_metadata
    
    for package in REQUIRED_PACKAGES:
        try:
            importlib_metadata.distribution(package)
        except importlib_metadata.PackageNotFoundError:
            missing_packages.append(package)
    
    if missing_packages:
        print(f"Installing missing packages: {', '.join(missing_packages)}")
        subprocess.check_call([sys.executable, "-m", "pip", "install"] + missing_packages)
        print("All required packages installed successfully.")
        
        # Restart the application after installing packages
        python = sys.executable
        os.execl(python, python, *sys.argv)

# Install dependencies if needed
if __name__ == "__main__":
    check_and_install_dependencies()

# Now we can safely import from the required packages
import requests
from pygments import highlight
from pygments.lexers import get_lexer_by_name, get_all_lexers
from pygments.formatters import get_formatter_by_name
from pygments.styles import get_all_styles
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# LLM Settings
LLM_SETTINGS = ${JSON.stringify(llmSettings, null, 4)}
ACTIVE_LLM = "ollama"  # Default LLM provider

# Main application class
class CodeNexusApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Code Nexus Wizard")
        self.root.geometry("1200x800")
        self.root.minsize(800, 600)
        
        # Application components will be implemented here
        # For a full implementation, please download the complete script

# Run the application
if __name__ == "__main__":
    root = tk.Tk()
    app = CodeNexusApp(root)
    root.mainloop()
`;
};
