// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwljmjknmnvbessdcijg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3bGptamtubW52YmVzc2RjaWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDU3MzIsImV4cCI6MjA2MDIyMTczMn0.9J9tPaX_83GjSdHAFvC-9UU2eib2Kfj6_IY1HjGSjaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);